name : Continous Integration and Deployment

on: 
 push:
   branches:
     - main

env:
 DOTNET_VERSION: "5.0.x"
 AZURE_WEBAPP_NAME: MyGithubActionsTest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
           dotnet-versions: ${{ env.DOTNET_VERSION }}  

      - name: Start Sql Server
        run: |
             docker run -d -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Pipp0ne!" -p 1433:1433 -d mcr.microsoft.com/mssql/server:latest     

      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'      

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore  

      - name: Run automated tests
        env: 
          ConnectionStrings_DefaultConnection: Server=localhost;Database=CustomerBook_Test;User=sa;Password=Pipp0ne!
        run: dotnet test -c Release --no-build

      - name: Publish app
        run: dotnet publish -c Release -o  ./out
  
      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v2
        with: 
           app-name: ${{ env.AZURE_WEBAPP_NAME }}
           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_SECRET }}
           package: ./out


          

